apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: formicae
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - configmap.yaml
  - secret.example.yaml
  - postgres.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-cronjob.yaml
images:
  - name: hhnl-formicae-api
    newName: docker.io/limeray/hhnl-formicae-api
    newTag: latest
  - name: hhnl-formicae-worker
    newName: docker.io/limeray/hhnl-formicae-worker
    newTag: latest
