apiVersion: batch/v1
kind: CronJob
metadata:
  name: formicae-worker
  labels:
    app.kubernetes.io/name: hhnl-formicae
    app.kubernetes.io/component: worker
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app.kubernetes.io/name: hhnl-formicae
            app.kubernetes.io/component: worker
        spec:
          serviceAccountName: formicae
          restartPolicy: Never
          containers:
            - name: worker
              image: hhnl-formicae-worker
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: formicae-config
                - secretRef:
                    name: formicae-secrets
              resources:
                requests:
                  cpu: 50m
                  memory: 96Mi
                limits:
                  cpu: 250m
                  memory: 256Mi
