{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "formicae.fullname" . }}-secrets
  labels:
    {{- include "formicae.labels" . | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__Formicae: {{ .Values.secrets.connectionString | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
{{- end -}}
