{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "formicae.serviceAccountName" . }}
  labels:
    {{- include "formicae.labels" . | nindent 4 }}
{{- end -}}
