import { expect, test, type Page, type APIRequestContext } from "@playwright/test";
const api="http://127.0.0.1:5000";
async function environment(request:APIRequestContext,name="Limited runtime") { const response=await request.post(`${api}/api/environments`,{data:{name:`${name} ${Date.now()}`,description:"Bound each AI task",configuration:{schemaVersion:1,runtime:{timeoutLimitSeconds:90},image:null,tools:[],mcpServers:[]}}});expect(response.ok(),await response.text()).toBeTruthy();return response.json(); }
async function definition(request:APIRequestContext,defaultEnvironmentId?:string) { const item=await(await request.post(`${api}/api/workflow-definitions`,{data:{name:`Environment workflow ${Date.now()}`}})).json();const response=await request.post(`${api}/api/workflow-definitions/${item.id}/versions`,{data:{isEnabled:true,isDefault:false,definition:{schema:"formicae.workflow/v1alpha3",startStepId:"plan",defaultEnvironmentId,editor:{positions:{plan:{x:100,y:120}},viewport:{x:60,y:40,zoom:1}},steps:[{id:"plan",uses:"builtins.plan",displayName:"Plan"}]}}});expect(response.ok(),await response.text()).toBeTruthy();return item; }
async function open(page:Page,name:string) { await page.goto("/workflow-definitions");await page.locator(".editor-workflow-name").click();await page.getByRole("complementary",{name:"Choose workflow"}).getByRole("button",{name,exact:true}).click();await expect(page.locator(".editor-save-status")).toHaveText("Saved");await page.getByRole("button",{name:"Workflow settings",exact:true}).click(); }
async function latest(request:APIRequestContext,id:string) { return (await(await request.get(`${api}/api/workflow-definitions/${id}`)).json()).versions[0].definition; }

test("environment catalog preserves default and conflicting runtime edits",async({page,request},testInfo)=>{
  await page.goto("/environments");await page.getByRole("complementary",{name:"Environment catalog"}).getByRole("button",{name:/Built-in/}).click();await expect(page.getByLabel("Environment name",{exact:true})).toBeDisabled();await expect(page.getByRole("button",{name:"Delete environment",exact:true})).toHaveCount(0);
  await page.getByRole("button",{name:"New environment",exact:true}).click();const name=`Environment catalog ${Date.now()}`;await page.getByLabel("Environment name",{exact:true}).fill(name);await page.getByLabel("Limit task runtime",{exact:true}).check();await page.getByLabel("Maximum task runtime (seconds)",{exact:true}).fill("120");await page.getByRole("button",{name:"Save environment",exact:true}).click();await expect(page.getByText("Environment saved.",{exact:true})).toBeVisible();
  const saved=(await(await request.get(`${api}/api/environments`)).json()).find((item:{name:string})=>item.name===name);expect(saved.configuration.runtime.timeoutLimitSeconds).toBe(120);expect((await request.put(`${api}/api/environments/${saved.id}`,{data:{...saved,expectedRevision:1,description:"External edit"}})).ok()).toBeTruthy();
  await page.getByLabel("Description",{exact:true}).fill("Unsaved local edit");await page.getByRole("button",{name:"Save environment",exact:true}).click();await expect(page.getByText(/Your edits are retained/)).toBeVisible();
  await page.route("**/api/environments",route=>route.fulfill({status:503,json:{error:"Environment catalog unavailable"}}));await page.getByRole("button",{name:"Reload current revision",exact:true}).click();await page.getByRole("dialog").getByRole("button",{name:"Discard",exact:true}).click();await expect(page.getByLabel("Description",{exact:true})).toHaveValue("Unsaved local edit");await page.unroute("**/api/environments");
  let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});await page.route("**/api/environments",async route=>{await gate;await route.continue();});await page.getByRole("button",{name:"Reload current revision",exact:true}).click();await page.getByRole("dialog").getByRole("button",{name:"Discard",exact:true}).click();await expect(page.getByLabel("Environment name",{exact:true})).toBeDisabled();release();await expect(page.getByLabel("Description",{exact:true})).toHaveValue("External edit");await page.unroute("**/api/environments");
  for(const width of [1600,800]){await page.setViewportSize({width,height:900});if(width===800)await expect.poll(async()=>page.locator(".side-nav").evaluate(el=>el.getBoundingClientRect().right)).toBeLessThanOrEqual(1);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:testInfo.outputPath(`environments-${width}.png`),fullPage:true});}
  await page.getByRole("button",{name:"Delete environment",exact:true}).click();await expect(page.getByRole("dialog")).toContainText("Existing workflow versions retain");await page.screenshot({path:testInfo.outputPath("environment-delete.png")});await page.getByRole("dialog").getByRole("button",{name:"Delete",exact:true}).click();await expect(page.getByText(/Environment deleted/)).toBeVisible();
});

test("workflow environment snapshots preserve positions and saved revision through undo",async({page,request},testInfo)=>{
  const selected=await environment(request),item=await definition(request);await open(page,item.name);await expect(page.getByLabel("Workflow environment",{exact:true})).toHaveValue("default");await page.getByLabel("Workflow environment",{exact:true}).selectOption(selected.id);await page.getByRole("button",{name:"Save Version",exact:true}).click();await expect(page.locator(".editor-save-status")).toHaveText("Saved");const doc=await latest(request,item.id);expect(doc.defaultEnvironmentSnapshot.id).toBe(selected.id);expect(doc.defaultEnvironmentSnapshot.configuration.runtime.timeoutLimitSeconds).toBe(90);expect(doc.editor.positions.plan).toEqual({x:100,y:120});
  expect((await request.put(`${api}/api/environments/${selected.id}`,{data:{...selected,expectedRevision:1,configuration:{...selected.configuration,runtime:{timeoutLimitSeconds:30}}}})).ok()).toBeTruthy();await page.getByRole("button",{name:"Refresh",exact:true}).click();await expect(page.getByText("Saved version uses environment revision 1; Save Version will use revision 2.")).toBeVisible();await page.getByText("Profile for next save · revision 2",{exact:true}).click();await expect(page.getByText("Saved runtime limit: 90 seconds.",{exact:true})).toBeVisible();await page.getByLabel("Workflow environment",{exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:testInfo.outputPath("environment-revision.png")});
  await page.getByLabel("Enabled",{exact:true}).uncheck();await page.getByRole("button",{name:"Save Version",exact:true}).click();await expect(page.locator(".editor-save-status")).toHaveText("Saved");await page.getByRole("button",{name:"Undo",exact:true}).click();await expect(page.getByText(`Saved environment: ${selected.name} · revision 2`,{exact:true})).toBeVisible();await page.getByRole("button",{name:"Redo",exact:true}).click();await open(page,item.name);await expect(page.getByLabel("Workflow environment",{exact:true})).toHaveValue(selected.id);
});

test("deleted environment stays runnable in saved version and can remain in disabled draft",async({page,request})=>{
  const selected=await environment(request),item=await definition(request,selected.id);expect((await request.delete(`${api}/api/environments/${selected.id}?expectedRevision=1`)).ok()).toBeTruthy();await open(page,item.name);await expect(page.getByText(/saved version remains runnable with its recorded environment/)).toBeVisible();await page.getByLabel("Enabled",{exact:true}).uncheck();await page.getByRole("button",{name:"Save Version",exact:true}).click();await expect(page.locator(".editor-save-status")).toHaveText("Saved");expect((await latest(request,item.id)).defaultEnvironmentId).toBe(selected.id);await page.getByLabel("Workflow environment",{exact:true}).selectOption("default");await page.getByLabel("Enabled",{exact:true}).check();await page.getByRole("button",{name:"Save Version",exact:true}).click();await expect(page.locator(".editor-save-status")).toHaveText("Saved");expect((await latest(request,item.id)).defaultEnvironmentSnapshot.id).toBe("default");
  const invalid=await request.post(`${api}/api/workflow-definitions/${item.id}/versions`,{data:{isEnabled:false,isDefault:false,definition:{...await latest(request,item.id),defaultEnvironmentId:""}}});expect(invalid.ok()).toBeTruthy();await open(page,item.name);await expect(page.getByLabel("Workflow environment",{exact:true})).toHaveValue("");await expect(page.getByLabel("Workflow environment",{exact:true}).locator("option:checked")).toHaveText("Unavailable: empty environment ID");await page.getByRole("button",{name:"Save Version",exact:true}).click();await expect(page.locator(".editor-save-status")).toHaveText("Saved");expect((await latest(request,item.id)).defaultEnvironmentId).toBe("");
});

test("environment selection made during save stays dirty and does not inherit stale snapshot",async({page,request})=>{
  const first=await environment(request,"First profile"),second=await environment(request,"Second profile"),item=await definition(request);await open(page,item.name);await page.getByLabel("Workflow environment",{exact:true}).selectOption(first.id);
  let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});await page.route(`**/api/workflow-definitions/${item.id}/versions`,async route=>{await gate;await route.continue();});await page.getByRole("button",{name:"Save Version",exact:true}).click();await expect(page.getByRole("button",{name:"Save Version",exact:true})).toBeDisabled();await page.getByLabel("Workflow environment",{exact:true}).selectOption(second.id);release();await expect(page.getByRole("button",{name:"Save Version",exact:true})).toBeEnabled();await expect(page.locator(".editor-save-status")).toHaveText("Unsaved changes");await expect(page.getByLabel("Workflow environment",{exact:true})).toHaveValue(second.id);await expect(page.getByText(`Saved environment: ${first.name} · revision 1`,{exact:true})).toHaveCount(0);expect((await latest(request,item.id)).defaultEnvironmentSnapshot.id).toBe(first.id);
});

test("workflow viewers inspect environments but cannot change configuration",async({page,request})=>{
  const selected=await environment(request),item=await definition(request,selected.id);await page.route("**/api/auth/current-user",async route=>{const response=await route.fetch();await route.fulfill({json:{...await response.json(),canAdminister:false,canViewWorkflows:true}});});await page.goto("/environments");await page.getByRole("complementary",{name:"Environment catalog"}).getByRole("button",{name:new RegExp(selected.name)}).click();await expect(page.getByLabel("Maximum task runtime (seconds)",{exact:true})).toBeDisabled();await expect(page.getByRole("button",{name:"Save environment",exact:true})).toBeDisabled();await open(page,item.name);await expect(page.getByLabel("Workflow environment",{exact:true})).toBeDisabled();
});

test("environment history labels pinned constraints without inventing job settings",async({page},testInfo)=>{
  const id="11111111-1111-1111-1111-111111111111",time="2026-09-06T10:00:00Z",workflow={workflowId:id,issueUrl:"https://example.com/issues/1",repositoryUrl:"https://example.com/repo",status:"Running",currentStep:"Custom",createdAt:time,updatedAt:time};await page.route("**/api/workflows**",route=>{const path=new URL(route.request().url()).pathname;const json=path.endsWith("/events")?[{id:"settings",type:"TaskSettingsResolved",level:"Info",createdAt:time,message:"Task settings resolved",detailsJson:JSON.stringify({taskRunId:"run1",executionAttemptId:"attempt1",environment:{id:"deleted-profile",revision:2,name:"Recorded profile",timeoutLimitSeconds:45}})}]:path==="/api/workflows"?[workflow]:path===`/api/workflows/${id}`?workflow:[];return route.fulfill({json});});await page.goto("/workflows");const history=page.getByRole("region",{name:"Environment profile configuration"});await expect(history).toContainText("Recorded profile · revision 2");await expect(history).toContainText("Saved timeout limit: 45 seconds");await expect(history).toContainText("not observed job settings");await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:testInfo.outputPath("environment-history.png"),fullPage:true});
});
