import { expect, test, type Page } from "@playwright/test";
const api = "http://127.0.0.1:5000";
async function open(page: Page, name: string) {
 await page.goto("/workflow-definitions"); await page.locator(".editor-workflow-name").click();
 await page.getByRole("complementary", { name: "Choose workflow" }).getByRole("button", { name, exact: true }).click();
 await expect(page.locator(".editor-save-status")).toHaveText("Saved");
}
async function inspect(page: Page, id: string) { await page.getByLabel("Find a node").fill(id); await page.locator(".editor-search-results").getByRole("button", { name: new RegExp(`\\(${id}\\)$`) }).click(); }

test("environment extensions save structured image tool and credential references and remain read only for viewers", async ({ page, request }) => {
 const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
 const minimalName = `Native optional settings ${Date.now()}`;
 const minimalResponse = await request.post(`${api}/api/environments`, { data: { name: minimalName, configuration: { schemaVersion: 1, image: { reference: "example/worker:1" }, tools: [], mcpServers: [{ name: "local", command: "node" }] } } }); expect(minimalResponse.ok(), await minimalResponse.text()).toBeTruthy();
 await page.goto("/environments"); await page.getByRole("complementary", { name: "Environment catalog" }).getByRole("button", { name: new RegExp(minimalName) }).click(); await expect(page.getByLabel("Image reference", { exact: true })).toHaveValue("example/worker:1"); await expect(page.getByLabel("Image pull policy")).toHaveValue("IfNotPresent"); await expect(page.getByLabel("Image pull secret names (one per line)")).toHaveValue(""); await expect(page.getByRole("button", { name: "Add MCP 1 argument", exact: true })).toBeVisible(); await page.getByLabel("Image reference", { exact: true }).fill("example/worker:2"); await page.getByRole("button", { name: "Save environment", exact: true }).click(); await expect(page.getByText("Environment saved.", { exact: true })).toBeVisible(); expect(errors).toEqual([]);
 await page.goto("/environments"); await page.getByRole("button", { name: "New environment", exact: true }).click();
 const name = `Extended environment ${Date.now()}`; await page.getByLabel("Environment name", { exact: true }).fill(name);
 await page.getByLabel("Use custom execution image").check(); await page.getByLabel("Image reference", { exact: true }).fill("ghcr.io/anhaehne/formicae-worker:0.20.0");
 await page.getByLabel("Image pull policy").selectOption("Always"); await page.getByLabel("Image pull secret names (one per line)").fill("registry-auth");
 await page.getByRole("button", { name: "Add tool install" }).click(); await page.getByLabel("Tool name 1", { exact: true }).fill("jq"); await page.getByLabel("Install script 1").fill("command -v jq"); await page.getByLabel("Install timeout seconds 1").fill("60");
 await page.getByRole("button", { name: "Add MCP server", exact: true }).click(); await page.getByLabel("MCP name 1", { exact: true }).fill("issues"); await page.getByLabel("MCP transport 1").selectOption("http"); await page.getByLabel("MCP URL 1").fill("https://mcp.example.com/api"); await page.getByLabel("MCP bearer token secret alias 1").fill("ISSUES_TOKEN");
 await page.getByRole("button", { name: "Add MCP 1 header secret aliases", exact: true }).click(); await page.getByLabel("MCP 1 header secret aliases name 1").fill("X-Token"); await page.getByLabel("MCP 1 header secret aliases secret alias 1").fill("ISSUES_TOKEN");
 await page.getByLabel("Image reference", { exact: true }).fill("bad image with spaces"); await page.getByRole("button", { name: "Save environment", exact: true }).click(); await expect(page.getByRole("alert")).toContainText("Image reference"); await expect(page.getByLabel("Install script 1")).toHaveValue("command -v jq");
 await page.getByLabel("Image reference", { exact: true }).fill("ghcr.io/anhaehne/formicae-worker:0.20.0"); await page.getByRole("button", { name: "Save environment", exact: true }).click(); await expect(page.getByText("Environment saved.", { exact: true })).toBeVisible();
 const saved = (await (await request.get(`${api}/api/environments`)).json()).find((item: { name: string }) => item.name === name);
 expect(saved.configuration.image).toEqual({ reference: "ghcr.io/anhaehne/formicae-worker:0.20.0", pullPolicy: "Always", pullSecretNames: ["registry-auth"] });
 expect(saved.configuration.tools[0]).toEqual({ name: "jq", script: "command -v jq", shell: "sh", timeoutSeconds: 60 });
 expect(saved.configuration.mcpServers[0]).toMatchObject({ name: "issues", transport: "http", bearerTokenEnvironmentVariable: "ISSUES_TOKEN", headerEnvironmentVariables: { "X-Token": "ISSUES_TOKEN" } });
 await page.getByLabel("Install script 1").fill("local unsaved change"); await page.getByRole("button", { name: "Cancel edits", exact: true }).click(); await page.getByRole("dialog").getByRole("button", { name: "Discard", exact: true }).click(); await expect(page.getByLabel("Install script 1")).toHaveValue("command -v jq");
 await page.route("**/api/auth/current-user", async route => { const response = await route.fetch(); await route.fulfill({ json: { ...await response.json(), canAdminister: false, canViewWorkflows: true } }); });
 await page.reload(); await page.getByRole("complementary", { name: "Environment catalog" }).getByRole("button", { name: new RegExp(name) }).click();
 await expect(page.getByLabel("Image reference", { exact: true })).toBeDisabled(); await expect(page.getByLabel("Install script 1")).toBeDisabled(); await expect(page.getByLabel("MCP bearer token secret alias 1")).toBeDisabled(); await expect(page.getByRole("button", { name: "Add tool install" })).toBeDisabled(); expect(errors).toEqual([]);
});

test("script editor preserves capability distinction secret references and script output binding through undo and reload", async ({ page, request }) => {
 const taskResponse = await request.post(`${api}/api/custom-tasks`, { data: { name: `Script consumer ${Date.now()}`, description: "Consume script output", promptTemplate: "Result: {{input.result}}", inputs: [{ name: "result", valueType: "string", required: true }], outputs: [], runner: { kind: "agent", timeoutSeconds: 300 } } }); expect(taskResponse.ok(), await taskResponse.text()).toBeTruthy(); const task = await taskResponse.json();
 const item = await (await request.post(`${api}/api/workflow-definitions`, { data: { name: `Script editor ${Date.now()}` } })).json();
 const version = await request.post(`${api}/api/workflow-definitions/${item.id}/versions`, { data: { isEnabled: true, isDefault: false, definition: { schema: "formicae.workflow/v1alpha3", startStepId: "script", steps: [{ id: "script", uses: "builtins.script", displayName: "Run script", nextStepId: "consumer", script: { shell: "sh", script: "printf hello", timeoutSeconds: 30, workingDirectory: "workspace" } }, { id: "consumer", uses: "builtins.custom-task", displayName: "Consumer", customTask: { taskId: task.id, inputs: {}, bindings: { result: { stepId: "script", outputName: "output" } } } }] } } }); expect(version.ok(), await version.text()).toBeTruthy();
 await open(page, item.name); await inspect(page, "script"); await expect(page.getByLabel("Script body")).toHaveValue("printf hello"); await expect(page.getByLabel("Step persona", { exact: true })).toHaveCount(0); await expect(page.getByLabel("Capability policy")).toHaveValue("inherit");
 await page.getByLabel("Capability policy").selectOption("restricted"); await expect(page.getByText("No managed capabilities selected.")).toBeVisible(); await expect(page.getByLabel("Allow browser")).toHaveCount(0);
 await page.getByRole("button", { name: "Add secret reference", exact: true }).click(); await page.getByLabel("Secret environment alias 1").fill("TASK_TOKEN"); await page.getByLabel("Secret resource name 1").fill("task-secret"); await page.getByLabel("Secret key 1").fill("token");
 await page.getByLabel("Script shell").selectOption("bash"); await page.getByLabel("Script body").fill("printf updated"); await page.getByLabel("Script timeout seconds").fill("45"); await page.getByLabel("Script body").click(); await page.getByRole("button", { name: "Save Version", exact: true }).click(); await expect(page.locator(".editor-save-status")).toHaveText("Saved");
 const document = (await (await request.get(`${api}/api/workflow-definitions/${item.id}`)).json()).versions[0].definition;
 expect(document.steps[0]).toMatchObject({ capabilities: [], secretReferences: [{ environmentName: "TASK_TOKEN", secretName: "task-secret", key: "token" }], script: { shell: "bash", script: "printf updated", timeoutSeconds: 45 } }); expect(document.steps[0].model).toBeFalsy(); expect(document.steps[0].personaId).toBeFalsy();
 await page.getByLabel("Capability policy").selectOption("inherit"); await page.getByLabel("Script body").click(); await page.getByRole("button", { name: "Undo", exact: true }).click(); await expect(page.getByLabel("Capability policy")).toHaveValue("restricted");
 await page.reload(); await open(page, item.name); await inspect(page, "consumer"); await expect(page.getByLabel("Source for result")).toHaveValue(JSON.stringify(["script", "output"])); await expect(page.getByLabel("Source for result").locator("option:checked")).toContainText("Run script · output");
});

test("script investigation shows actual historical and current exit codes with pinned references", async ({ page }) => {
 const id = "11111111-1111-1111-1111-111111111111", time = "2026-10-06T10:00:00Z", workflow = { workflowId: id, issueUrl: "https://example.com/issues/1", repositoryUrl: "https://example.com/repo", status: "Completed", currentStep: "Script", createdAt: time, updatedAt: time };
 await page.route("**/api/workflows**", route => { const path = new URL(route.request().url()).pathname; if (path.endsWith("/logs/stream")) return route.fulfill({ contentType: "text/event-stream", body: "retry: 60000\n\n" });
 const json = path.endsWith("/execution") ? { workflow, definitionVersionId: "pinned", definition: { schema: "formicae.workflow/v1alpha3", startStepId: "script", steps: [{ id: "script", uses: "builtins.script", displayName: "Script", capabilities: [], secretReferences: [{ environmentName: "TASK_TOKEN", secretName: "task-secret", key: "token" }], script: { shell: "sh", script: "printf result", timeoutSeconds: 30, workingDirectory: "workspace" } }] }, runs: [{ id: "run1", workflowId: id, executionAttemptId: "current", attemptCount: 2, definitionStepId: "script", kind: "Script", status: "Succeeded", exitCode: 0, output: "result", createdAt: time, updatedAt: time, agentMessages: [] }], attempts: [{ id: "archive", workflowId: id, taskRunId: "run1", executionAttemptId: "first", attemptNumber: 1, definitionStepId: "script", status: "Failed", exitCode: 7, output: "failed result", failureReason: "Script exited with code 7", createdAt: time, updatedAt: time }], loops: [], decisions: [], control: { isPaused: false, canPause: false, canResume: false, canCancel: false } } : path.endsWith("/logs/page") ? { items: [], nextCursor: 0, previousCursor: 0, hasEarlier: false, hasMore: false } : path.endsWith("/search") ? { items: [workflow], totalCount: 1, offset: 0, limit: 25 } : path === "/api/workflows" ? [workflow] : []; return route.fulfill({ json }); });
 await page.goto(`/workflows?workflowId=${id}&node=script&attempt=first`); await expect(page.getByText("Exit code: 7", { exact: true })).toBeVisible(); await expect(page.getByRole("region", { name: "Script execution" })).toContainText("sh · 30s · workspace"); await page.getByLabel("Iteration and attempt").selectOption("current"); await expect(page.getByText("Exit code: 0", { exact: true })).toBeVisible(); await expect(page.getByText("Exit code: 7", { exact: true })).toHaveCount(0);
});

test("MCP step alias validation retains drafts and deleted profile metadata stays pinned", async ({ page, request }) => {
 const profileResponse = await request.post(`${api}/api/environments`, { data: { name: `Credential profile ${Date.now()}`, description: "Reference-only MCP", configuration: { schemaVersion: 1, runtime: null, image: { reference: "example/worker:1", pullPolicy: "IfNotPresent", pullSecretNames: [] }, tools: [{ name: "jq", script: "command -v jq", shell: "sh", timeoutSeconds: 30 }], mcpServers: [{ name: "issues", transport: "http", command: null, arguments: [], url: "https://mcp.example.com/api", environmentVariables: {}, bearerTokenEnvironmentVariable: "ISSUES_TOKEN", headerEnvironmentVariables: {} }] } } }); expect(profileResponse.ok(), await profileResponse.text()).toBeTruthy(); const profile = await profileResponse.json();
 const item = await (await request.post(`${api}/api/workflow-definitions`, { data: { name: `Alias validation ${Date.now()}` } })).json();
 const version = await request.post(`${api}/api/workflow-definitions/${item.id}/versions`, { data: { isEnabled: true, isDefault: false, definition: { schema: "formicae.workflow/v1alpha3", startStepId: "task", defaultEnvironmentId: profile.id, steps: [{ id: "task", uses: "builtins.plan", displayName: "Plan", secretReferences: [{ environmentName: "ISSUES_TOKEN", secretName: "issue-access", key: "token" }] }] } } }); expect(version.ok(), await version.text()).toBeTruthy();
 await open(page, item.name); await inspect(page, "task"); await page.getByLabel("Secret environment alias 1").fill("PATH"); await expect(page.getByRole("alert").filter({ hasText: "Add a secret reference for MCP alias ISSUES_TOKEN." })).toBeVisible(); await page.getByRole("button", { name: "Save Version", exact: true }).click(); await expect(page.getByRole("alert").filter({ hasText: /invalid or reserved/ }).first()).toBeVisible(); await expect(page.getByLabel("Secret environment alias 1")).toHaveValue("PATH"); await expect(page.locator(".editor-save-status")).toHaveText("Unsaved changes");
 await page.getByLabel("Secret environment alias 1").fill("ISSUES_TOKEN"); await expect(page.getByText("Add a secret reference for MCP alias ISSUES_TOKEN.", { exact: true })).toHaveCount(0); await page.getByLabel("Capability policy").selectOption("restricted"); await page.getByLabel("Allow mcp:issues").check(); await page.getByRole("button", { name: "Save Version", exact: true }).click(); await expect(page.locator(".editor-save-status")).toHaveText("Saved");
 expect((await request.delete(`${api}/api/environments/${profile.id}?expectedRevision=1`)).ok()).toBeTruthy(); await page.getByRole("button", { name: "Refresh", exact: true }).click(); await expect(page.getByText(/saved version remains runnable with its recorded environment/)).toBeVisible(); await page.getByText("Saved profile · revision 1", { exact: true }).click(); await expect(page.getByText("Execution image: example/worker:1", { exact: true })).toBeVisible(); await expect(page.getByText("Tools: jq", { exact: true })).toBeVisible(); await expect(page.getByText("MCP servers: issues", { exact: true })).toBeVisible(); await expect(page.getByLabel("Allow mcp:issues")).toBeChecked();
});

test("converting and duplicating an agent task clears incompatible script settings without changing the original", async ({ page, request }) => {
 const item = await (await request.post(`${api}/api/workflow-definitions`, { data: { name: `Task conversion ${Date.now()}` } })).json();
 const response = await request.post(`${api}/api/workflow-definitions/${item.id}/versions`, { data: { isEnabled: true, isDefault: false, definition: { schema: "formicae.workflow/v1alpha3", startStepId: "task", steps: [{ id: "task", uses: "builtins.plan", displayName: "Convertible", model: "previous-model", personaId: "default", capabilities: ["browser"] }] } } }); expect(response.ok(), await response.text()).toBeTruthy();
 await open(page, item.name); await inspect(page, "task"); await page.getByLabel("Task", { exact: true }).selectOption("builtins.script"); await page.getByLabel("Script body").fill("printf original"); await expect(page.getByLabel("Step persona", { exact: true })).toHaveCount(0); await expect(page.getByLabel("Capability policy")).toHaveValue("inherit");
 await page.getByRole("button", { name: "Save Version", exact: true }).click(); await expect(page.locator(".editor-save-status")).toHaveText("Saved");
 const saved = (await (await request.get(`${api}/api/workflow-definitions/${item.id}`)).json()).versions[0].definition.steps[0]; expect(saved.model).toBeFalsy(); expect(saved.aiSettingsId).toBeFalsy(); expect(saved.personaId).toBeFalsy(); expect(saved.personaSnapshot).toBeFalsy(); expect(saved.capabilities ?? null).toBeNull();
 await page.getByRole("button", { name: "Duplicate task", exact: true }).click(); await expect(page.getByLabel("Script body")).toHaveValue("printf original"); await page.getByLabel("Script body").fill("printf copy"); await inspect(page, "task"); await expect(page.getByLabel("Script body")).toHaveValue("printf original"); await inspect(page, "task-copy"); await expect(page.getByLabel("Script body")).toHaveValue("printf copy");
 await page.getByRole("button", { name: "+ Add Step", exact: true }).click(); await page.getByLabel("Search step types").fill("script"); await page.getByRole("complementary", { name: "Add step menu" }).getByRole("button", { name: /Script.*bounded shell/ }).click(); await expect(page.getByLabel("Script body")).toHaveValue(""); await expect(page.getByLabel("Script shell")).toHaveValue("sh"); await expect(page.getByLabel("Step persona", { exact: true })).toHaveCount(0);
});

test("MCP argument editing preserves empty and padded arguments and transport changes retain no incompatible bindings", async ({ page, request }) => {
 await page.goto("/environments"); await page.getByRole("button", { name: "New environment", exact: true }).click(); const name = `MCP arguments ${Date.now()}`; await page.getByLabel("Environment name", { exact: true }).fill(name); await page.getByRole("button", { name: "Add MCP server", exact: true }).click(); await page.getByLabel("MCP name 1", { exact: true }).fill("local"); await page.getByLabel("MCP command 1", { exact: true }).fill("node");
 await page.getByRole("button", { name: "Add MCP 1 argument", exact: true }).click(); await page.getByRole("button", { name: "Add MCP 1 argument", exact: true }).click(); await page.getByLabel("MCP 1 argument 2", { exact: true }).fill(" padded argument ");
 await page.getByRole("button", { name: "Add MCP 1 environment secret aliases", exact: true }).click(); await page.getByLabel("MCP 1 environment secret aliases name 1").fill("GH_TOKEN"); await page.getByLabel("MCP 1 environment secret aliases secret alias 1").fill("TASK_TOKEN"); await page.getByRole("button", { name: "Add MCP 1 environment secret aliases", exact: true }).click(); await page.getByLabel("MCP 1 environment secret aliases name 2").fill("GH_TOKEN"); await expect(page.getByRole("alert")).toContainText("Choose a unique name"); await expect(page.getByLabel("MCP 1 environment secret aliases secret alias 1")).toHaveValue("TASK_TOKEN"); await page.getByLabel("MCP 1 environment secret aliases name 2").fill("OTHER"); await page.getByLabel("MCP 1 environment secret aliases secret alias 2").fill("OTHER_TOKEN");
 await page.getByRole("button", { name: "Save environment", exact: true }).click(); await expect(page.getByText("Environment saved.", { exact: true })).toBeVisible(); const saved = (await (await request.get(`${api}/api/environments`)).json()).find((item: { name: string }) => item.name === name); expect(saved.configuration.mcpServers[0].arguments).toEqual(["", " padded argument "]); expect(saved.configuration.mcpServers[0].environmentVariables).toEqual({ GH_TOKEN: "TASK_TOKEN", OTHER: "OTHER_TOKEN" });
 await page.getByLabel("MCP transport 1").selectOption("http"); await page.getByLabel("MCP URL 1", { exact: true }).fill("https://mcp.example.com/api"); await expect(page.getByRole("button", { name: "Add MCP 1 environment secret aliases", exact: true })).toHaveCount(0); await page.getByRole("button", { name: "Save environment", exact: true }).click(); await expect(page.getByText("Environment saved.", { exact: true })).toBeVisible(); const updated = await (await request.get(`${api}/api/environments/${saved.id}`)).json(); expect(updated.configuration.mcpServers[0]).toMatchObject({ transport: "http", command: null, arguments: [], environmentVariables: {} });
});
