import { expect, test, type Page, type APIRequestContext } from "@playwright/test";
const api="http://127.0.0.1:5000";
async function environment(request:APIRequestContext,name="Limited runtime") { const response=await request.post(`${api}/api/environments`,{data:{name:`${name} ${Date.now()}`,description:"Bound each AI task",configuration:{schemaVersion:1,runtime:{timeoutLimitSeconds:90},image:null,tools:[],mcpServers:[]}}});expect(response.ok(),await response.text()).toBeTruthy();return response.json(); }
async function definition(request:APIRequestContext,defaultEnvironmentId?:string) { const item=await(await request.post(`${api}/api/workflow-definitions`,{data:{name:`Environment workflow ${Date.now()}`}})).json();const response=await request.post(`${api}/api/workflow-definitions/${item.id}/versions`,{data:{isEnabled:true,isDefault:false,definition:{schema:"formicae.workflow/v1alpha3",startStepId:"plan",defaultEnvironmentId,editor:{positions:{plan:{x:100,y:120}},viewport:{x:60,y:40,zoom:1}},steps:[{id:"plan",uses:"builtins.plan",displayName:"Plan"}]}}});expect(response.ok(),await response.text()).toBeTruthy();return item; }
async function open(page:Page,name:string) { await page.goto("/workflow-definitions");await page.locator(".editor-workflow-name").click();await page.getByRole("complementary",{name:"Choose workflow"}).getByRole("button",{name,exact:true}).click();await expect(page.locator(".editor-save-status")).toHaveText("Saved");await find(page,"plan"); }
async function latest(request:APIRequestContext,id:string) { return (await(await request.get(`${api}/api/workflow-definitions/${id}`)).json()).versions[0].definition; }

async function find(page:Page,id:string) { await page.getByLabel("Find a node").fill(id);await page.locator(".editor-search-results").getByRole("button",{name:new RegExp(`\\(${id}\\)$`)}).click(); }
async function save(page:Page) { await page.getByRole("button",{name:"Save Version",exact:true}).click();await expect(page.locator(".editor-save-status")).toHaveText("Saved"); }

test("step environments distinguish inheritance override and explicit default through save reload",async({page,request},testInfo)=>{
 const inherited=await environment(request,"Workflow cap"),override=await environment(request,"Step cap"),item=await definition(request,inherited.id);await open(page,item.name);const picker=page.getByLabel("Step environment",{exact:true});await expect(picker.locator("option:checked")).toHaveText("Inherit workflow environment");await expect(page.getByText(`Saved environment: ${inherited.name} · revision 1`,{exact:true})).toBeVisible();
 await picker.selectOption(override.id);await save(page);let doc=await latest(request,item.id);expect(doc.steps[0].environmentId).toBe(override.id);expect(doc.steps[0].environmentSnapshot.id).toBe(override.id);expect(doc.defaultEnvironmentSnapshot.id).toBe(inherited.id);await open(page,item.name);await expect(picker).toHaveValue(override.id);
 for(const width of [1600,800]) { await page.setViewportSize({width,height:900});if(width===800)await expect.poll(async()=>page.locator(".side-nav").evaluate(el=>el.getBoundingClientRect().right)).toBeLessThanOrEqual(1);await picker.scrollIntoViewIfNeeded();await page.screenshot({path:testInfo.outputPath(`step-environment-${width}.png`),fullPage:true}); }
 await picker.selectOption("default");await save(page);doc=await latest(request,item.id);expect(doc.steps[0].environmentId).toBe("default");expect(doc.steps[0].environmentSnapshot.id).toBe("default");await picker.selectOption({label:"Inherit workflow environment"});await save(page);doc=await latest(request,item.id);expect(doc.steps[0].environmentId??null).toBeNull();expect(doc.steps[0].environmentSnapshot.id).toBe(inherited.id);
});

test("step environment revisions undo duplication and non AI clearing use saved baseline",async({page,request})=>{
 const profile=await environment(request),item=await definition(request);await open(page,item.name);const picker=page.getByLabel("Step environment",{exact:true});await picker.selectOption(profile.id);await save(page);expect((await request.put(`${api}/api/environments/${profile.id}`,{data:{...profile,expectedRevision:1,description:"New revision"}})).ok()).toBeTruthy();await page.getByRole("button",{name:"Refresh",exact:true}).click();await expect(page.getByText("Saved version uses environment revision 1; Save Version will use revision 2.")).toBeVisible();await page.getByLabel("Display Name",{exact:true}).fill("Renamed");await save(page);await page.getByRole("button",{name:"Undo",exact:true}).click();await expect(page.getByText(`Saved environment: ${profile.name} · revision 2`,{exact:true})).toBeVisible();await page.getByRole("button",{name:"Redo",exact:true}).click();await page.getByRole("button",{name:"Duplicate task",exact:true}).click();await expect(picker).toHaveValue(profile.id);await page.getByLabel("Task",{exact:true}).selectOption("builtins.create-pull-request");await expect(picker).toHaveCount(0);await page.getByRole("button",{name:"Undo",exact:true}).click();await expect(picker).toHaveValue(profile.id);
});

test("step environment delayed save preserves newer override selection",async({page,request})=>{
 const first=await environment(request,"First"),second=await environment(request,"Second"),item=await definition(request);await open(page,item.name);const picker=page.getByLabel("Step environment",{exact:true});await picker.selectOption(first.id);let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);await page.route(`**/api/workflow-definitions/${item.id}/versions`,async route=>{await gate;await route.continue();});await page.getByRole("button",{name:"Save Version",exact:true}).click();await expect(page.getByRole("button",{name:"Save Version",exact:true})).toBeDisabled();await picker.selectOption(second.id);release();await expect(page.getByRole("button",{name:"Save Version",exact:true})).toBeEnabled();await expect(page.locator(".editor-save-status")).toHaveText("Unsaved changes");await expect(picker).toHaveValue(second.id);await expect(page.getByText(`Saved environment: ${first.name} · revision 1`,{exact:true})).toHaveCount(0);expect((await latest(request,item.id)).steps[0].environmentSnapshot.id).toBe(first.id);
});

test("unavailable step environment remains inspectable in disabled versions and readonly",async({page,request})=>{
 const item=await definition(request);const doc=await latest(request,item.id);doc.steps[0].environmentId="";const response=await request.post(`${api}/api/workflow-definitions/${item.id}/versions`,{data:{isEnabled:false,isDefault:false,definition:doc}});expect(response.ok()).toBeTruthy();await open(page,item.name);const picker=page.getByLabel("Step environment",{exact:true});await expect(picker.locator("option:checked")).toHaveText("Unavailable: empty environment ID");await save(page);expect((await latest(request,item.id)).steps[0].environmentId).toBe("");await page.route("**/api/auth/current-user",async route=>{const response=await route.fetch();await route.fulfill({json:{...await response.json(),canAdminister:false,canViewWorkflows:true}});});await open(page,item.name);await expect(picker).toBeDisabled();
});

test("task cards show each pinned environment from its own settings event",async({page},testInfo)=>{
 const id="11111111-1111-1111-1111-111111111111",time="2026-09-06T10:00:00Z",workflow={workflowId:id,issueUrl:"https://example.com/issues/1",repositoryUrl:"https://example.com/repo",status:8,currentStep:6,createdAt:time,updatedAt:time};await page.route("**/api/workflows**",route=>{const path=new URL(route.request().url()).pathname;const json=path.endsWith("/runs")?[1,2].map(n=>({id:`run${n}`,kind:0,status:"Succeeded",definitionStepId:`plan${n}`,updatedAt:time,agentMessages:[]})):path.endsWith("/events")?[1,2].map(n=>({id:`event${n}`,taskRunId:`run${n}`,type:"AgentSettingsResolved",level:"Info",createdAt:time,message:"Settings resolved",detailsJson:JSON.stringify({environment:{id:`env${n}`,revision:n,name:`Pinned profile ${n}`,timeoutLimitSeconds:n*30}})})):path==="/api/workflows"?[workflow]:path===`/api/workflows/${id}`?workflow:[];return route.fulfill({json});});await page.goto("/workflows");for(const n of [1,2]) { const card=page.locator(".run-card").filter({hasText:`plan${n}`});await expect(card.getByRole("region",{name:"Environment profile configuration"})).toContainText(`Pinned profile ${n} · revision ${n}`); }await page.screenshot({path:testInfo.outputPath("step-environment-history.png"),fullPage:true});
});


test("legacy inherited step preview retains the saved document profile after deletion",async({page,request})=>{
 const profile=await environment(request),item=await definition(request,profile.id);await page.route(`**/api/workflow-definitions/${item.id}`,async route=>{const response=await route.fetch(),json=await response.json();for(const version of json.versions)for(const step of version.definition.steps){delete step.environmentId;delete step.environmentSnapshot;}await route.fulfill({json});});expect((await request.put(`${api}/api/environments/${profile.id}`,{data:{...profile,expectedRevision:1,description:"Catalog revision 2"}})).ok()).toBeTruthy();await open(page,item.name);await expect(page.getByText("Saved version uses environment revision 1; Save Version will use revision 2.")).toBeVisible();expect((await request.delete(`${api}/api/environments/${profile.id}?expectedRevision=2`)).ok()).toBeTruthy();await page.getByRole("button",{name:"Refresh",exact:true}).click();await expect(page.getByText(/saved version remains runnable with its recorded environment/)).toBeVisible();await expect(page.getByText(`Saved environment: ${profile.name} · revision 1`,{exact:true})).toBeVisible();
});
