import type { EnvironmentSnapshot, StepSecretReference, WorkflowScriptSettings } from "../api";
export const defaultScript: WorkflowScriptSettings = { shell: "sh", script: "", timeoutSeconds: 300, workingDirectory: "workspace" };
export function ScriptSettings({ value, disabled, onChange }: { value?: WorkflowScriptSettings | null; disabled: boolean; onChange: (value: WorkflowScriptSettings) => void }) {
 const settings = value ?? defaultScript;
 return <section className="editor-property-section" aria-label="Script settings"><h4>Script</h4><label><span>Script shell</span><select disabled={disabled} value={settings.shell} onChange={event => onChange({ ...settings, shell: event.target.value as "sh" | "bash" })}><option>sh</option><option>bash</option></select></label><label><span>Script body</span><textarea rows={8} disabled={disabled} value={settings.script} onChange={event => onChange({ ...settings, script: event.target.value })} /></label><label><span>Script timeout seconds</span><input type="number" min={1} max={3600} disabled={disabled} value={settings.timeoutSeconds} onChange={event => onChange({ ...settings, timeoutSeconds: Number(event.target.value) })} /></label><label><span>Script working directory</span><select disabled={disabled} value={settings.workingDirectory} onChange={event => onChange({ ...settings, workingDirectory: event.target.value as "workspace" | "repository" })}><option value="workspace">Scratch workspace</option><option value="repository">Checked-out repository</option></select></label><p className="muted">Runs in an ephemeral worker without an AI model. Output and the actual exit code are retained; nonzero exits fail the task. Repository changes are not automatically committed or pushed.</p></section>;
}
export function ExecutionSettings({ capabilities, references, environment, script, disabled, onChange }: { capabilities?: string[] | null; references?: StepSecretReference[] | null; environment?: EnvironmentSnapshot | null; script: boolean; disabled: boolean; onChange: (values: { capabilities?: string[] | null; secretReferences?: StepSecretReference[] }) => void }) {
 const refs = references ?? [], options = [...(script ? [] : ["browser", "nested-containers"]), ...(environment?.configuration.tools ?? []).map(item => `tool:${item.name}`), ...(script ? [] : (environment?.configuration.mcpServers ?? []).map(item => `mcp:${item.name}`))];
 const available = [...new Set([...options, ...(capabilities ?? [])])];
 const selectedServers = script ? [] : (environment?.configuration.mcpServers ?? []).filter(item => capabilities == null || capabilities.includes(`mcp:${item.name}`));
 const aliases = new Set(refs.map(item => item.environmentName));
 const required = [...new Set(selectedServers.flatMap(item => [...Object.values(item.environmentVariables ?? {}), ...Object.values(item.headerEnvironmentVariables ?? {}), ...(item.bearerTokenEnvironmentVariable ? [item.bearerTokenEnvironmentVariable] : [])]))];
 return <section className="editor-property-section" aria-label="Task access"><h4>Task access</h4><label><span>Capability policy</span><select disabled={disabled} value={capabilities == null ? "inherit" : "restricted"} onChange={event => onChange({ capabilities: event.target.value === "inherit" ? null : [] })}><option value="inherit">Default task capabilities</option><option value="restricted">Select allowed capabilities</option></select></label>
 <p className="muted">Controls Formicae-managed resources. This policy does not sandbox shell commands or network access. {script ? "Default provisions all profile tool installs." : "Default provisions profile tools and MCP servers, with browser and nested containers for tasks that use them."}</p>
 {capabilities != null && <fieldset><legend>Allowed capabilities</legend>{available.map(capability => <label className="toggle-label" key={capability}><input type="checkbox" aria-label={`Allow ${capability}`} disabled={disabled} checked={capabilities.includes(capability)} onChange={event => onChange({ capabilities: event.target.checked ? [...capabilities, capability] : capabilities.filter(item => item !== capability) })} /><span>{capability}{!options.includes(capability) ? " (unavailable for this task/profile)" : ""}</span></label>)}{!capabilities.length && <p>No managed capabilities selected.</p>}</fieldset>}
 <h4>External secret references</h4><p className="muted">Select existing worker-namespace Secret keys. Only reference names are saved; values are supplied at launch and masked in task evidence.</p>{refs.map((reference, index) => <fieldset key={index}><legend>Secret reference {index + 1}</legend>{([['environmentName','Secret environment alias'],['secretName','Secret resource name'],['key','Secret key']] as const).map(([key,label]) => <label key={key}><span>{label} {index + 1}</span><input disabled={disabled} value={reference[key]} onChange={event => onChange({ secretReferences: refs.map((item,i) => i === index ? { ...item, [key]: event.target.value } : item) })} /></label>)}<button type="button" disabled={disabled} onClick={() => onChange({ secretReferences: refs.filter((_,i) => i !== index) })}>Remove secret reference {index + 1}</button></fieldset>)}<button type="button" disabled={disabled} onClick={() => onChange({ secretReferences: [...refs, { environmentName: "", secretName: "", key: "" }] })}>Add secret reference</button>
 {required.length > 0 && <p className="muted">Selected MCP servers require aliases: {required.join(", ")}.</p>}{required.filter(alias => !aliases.has(alias)).map(alias => <p role="alert" className="error-text" key={alias}>Add a secret reference for MCP alias {alias}.</p>)}
 </section>;
}
