import { useEffect, useState } from "react";
import { listImages, listImageBuilds, type ImageBuild, type ImageSelection, type ManagedImage, type PreparedImageSnapshot } from "../api";

export function ImagePicker({ value, snapshot, disabled, environment = false, onChange }: { value?: ImageSelection | null; snapshot?: PreparedImageSnapshot | null; disabled: boolean; environment?: boolean; onChange: (selection: ImageSelection | undefined) => void }) {
  const [images, setImages] = useState<ManagedImage[]>([]), [builds, setBuilds] = useState<ImageBuild[]>([]), [error, setError] = useState("");
  useEffect(() => { let active = true; listImages().then(items => { if (active) setImages(items); }).catch(e => { if (active) setError(String(e)); }); return () => { active = false; }; }, []);
  useEffect(() => { setBuilds([]); if (!value?.imageId) return; let active = true; listImageBuilds(value.imageId).then(items => { if (active) setBuilds(items.filter(x => x.state === "Ready")); }).catch(e => { if (active) setError(String(e)); }); return () => { active = false; }; }, [value?.imageId]);
  const mode = value?.mode ?? "inherit", selected = images.find(x => x.id === value?.imageId);
  return <section className="image-picker" aria-label="Execution image selection"><label><span>Execution image</span><select aria-label="Execution image" disabled={disabled} value={mode} onChange={e => onChange(e.target.value === "inherit" ? undefined : { mode: e.target.value as ImageSelection["mode"] })}>{!environment && <option value="inherit">Inherit environment image</option>}{environment && <option value="inherit">Configured image reference</option>}<option value="platform">Use platform image</option><option value="managed">Select prepared image</option></select></label>
    {error && <p role="alert">{error}</p>}
    {mode === "managed" && <><label><span>Prepared image</span><select aria-label="Prepared image" disabled={disabled} value={value?.imageId ?? ""} onChange={e => onChange({ mode: "managed", imageId: e.target.value })}><option value="">Select an image</option>{value?.imageId && !selected && <option value={value.imageId}>Unavailable: {snapshot?.name ?? value.imageId}</option>}{images.map(image => <option key={image.id} value={image.id}>{image.name}</option>)}</select></label><label><span>Prepared build</span><select aria-label="Prepared build" disabled={disabled || !value?.imageId} value={value?.buildId ?? ""} onChange={e => onChange({ ...value, mode: "managed", buildId: e.target.value })}><option value="">Select a Ready build</option>{value?.buildId && !builds.some(x => x.id === value.buildId) && <option value={value.buildId}>Saved build: {value.buildId.slice(0, 8)}</option>}{builds.map(build => <option key={build.id} value={build.id}>Source revision {build.sourceRevision} · {build.id.slice(0, 8)}</option>)}</select></label>{value?.imageId && builds.length === 0 && <p className="muted">Prepare a successful build in Manage → Images before saving a new selection.</p>}{snapshot && <p className="image-reference">Saved image: {snapshot.name} · source revision {snapshot.sourceRevision}<br /><code>{snapshot.reference}</code></p>}<p className="muted">Save Version pins this exact build. Rebuilds do not change saved versions or retries.</p></>}
    {mode === "platform" && <p className="muted">Uses the platform worker image. Environment tools, MCP servers and timeouts are retained.</p>}
  </section>;
}
