import { ImagePicker } from "./workflowEditor/ImagePicker";
import { useEffect, useRef, useState } from "react";
import type { EnvironmentConfiguration, EnvironmentMcpServer } from "./api";

const lines = (value: string) => value.split(/\r?\n/).map(item => item.trim()).filter(Boolean);
function StringList({ label, value, disabled, onChange }: { label: string; value: string[]; disabled: boolean; onChange: (value: string[]) => void }) {
 const [text, setText] = useState(value.join("\n")); const focused = useRef(false);
 useEffect(() => { if (!focused.current) setText(value.join("\n")); }, [value]);
 return <label><span>{label}</span><textarea disabled={disabled} value={text} onFocus={() => { focused.current = true; }} onBlur={() => { focused.current = false; setText(value.join("\n")); }} onChange={event => { setText(event.target.value); onChange(lines(event.target.value)); }} /></label>;
}
function Pairs({ label, value, disabled, onChange }: { label: string; value: Record<string, string>; disabled: boolean; onChange: (value: Record<string, string>) => void }) {
  const [error, setError] = useState("");
  return <fieldset><legend>{label}</legend>{error && <p role="alert" className="error-text">{error}</p>}{Object.entries(value).map(([name, item], index) => <div className="form-row" key={index}><label><span>{label} name {index + 1}</span><input disabled={disabled} value={name} onChange={event => { const next = event.target.value; if (next !== name && Object.hasOwn(value, next)) { setError("Choose a unique name; the existing mappings are retained."); return; } setError(""); onChange(Object.fromEntries(Object.entries(value).map(([key, val]) => [key === name ? next : key, val]))); }} /></label><label><span>{label} secret alias {index + 1}</span><input disabled={disabled} value={item} onChange={event => onChange({ ...value, [name]: event.target.value })} /></label><button className="secondary-button" type="button" disabled={disabled} onClick={() => onChange(Object.fromEntries(Object.entries(value).filter(([key]) => key !== name)))}>Remove {label} {index + 1}</button></div>)}<button className="secondary-button" type="button" disabled={disabled} onClick={() => { let key = "NAME"; while (Object.hasOwn(value, key)) key += "_"; onChange({ ...value, [key]: "" }); }}>Add {label}</button></fieldset>;
}
export function EnvironmentExtensions({ value, disabled, onChange }: { value: EnvironmentConfiguration; disabled: boolean; onChange: (value: EnvironmentConfiguration) => void }) {
  const tools = value.tools ?? [], servers = value.mcpServers ?? [];
  const server = (index: number, patch: Partial<EnvironmentMcpServer>) => onChange({ ...value, mcpServers: servers.map((item, i) => i === index ? { ...item, ...patch } : item) });
  return <>
    <ImagePicker environment value={value.imageSelection} snapshot={value.imageSnapshot} disabled={disabled} onChange={imageSelection => onChange({ ...value, imageSelection, imageSnapshot: undefined, image: imageSelection ? null : value.image })} />
    {!value.imageSelection && <section className="environment-extension" aria-label="Execution image"><h3>Execution image</h3><label className="toggle-label"><input type="checkbox" aria-label="Use custom execution image" disabled={disabled} checked={!!value.image} onChange={event => onChange({ ...value, image: event.target.checked ? { reference: "", pullPolicy: "IfNotPresent", pullSecretNames: [] } : null })} /><span>Use custom execution image</span></label>
      <p className="muted">Use a worker-compatible image built from the Formicae worker image. Saved workflows pin the image selection.</p>
      {value.image && <><label><span>Image reference</span><input required disabled={disabled} value={value.image.reference} onChange={event => onChange({ ...value, image: { ...value.image!, reference: event.target.value } })} /></label><label><span>Image pull policy</span><select disabled={disabled} value={value.image.pullPolicy} onChange={event => onChange({ ...value, image: { ...value.image!, pullPolicy: event.target.value as "Always" | "IfNotPresent" | "Never" } })}>{["IfNotPresent", "Always", "Never"].map(policy => <option key={policy}>{policy}</option>)}</select></label><StringList label="Image pull secret names (one per line)" disabled={disabled} value={value.image.pullSecretNames ?? []} onChange={pullSecretNames => onChange({ ...value, image: { ...value.image!, pullSecretNames } })} /><p className="muted">Names of existing Kubernetes image-pull Secrets in the worker namespace. Credential values stay outside Formicae.</p></>}
    </section>}
    <section className="environment-extension" aria-label="Tool installs"><h3>Tool installs</h3><p className="muted">Named bootstrap scripts run before the task. A failed install stops execution. Steps can select which tools to provision.</p>{tools.map((tool, index) => <fieldset key={index}><legend>Tool {index + 1}</legend><label><span>Tool name {index + 1}</span><input required disabled={disabled} value={tool.name} onChange={event => onChange({ ...value, tools: tools.map((item, i) => i === index ? { ...item, name: event.target.value } : item) })} /></label><label><span>Install shell {index + 1}</span><select disabled={disabled} value={tool.shell} onChange={event => onChange({ ...value, tools: tools.map((item, i) => i === index ? { ...item, shell: event.target.value as "sh" | "bash" } : item) })}><option>sh</option><option>bash</option></select></label><label><span>Install script {index + 1}</span><textarea required rows={5} disabled={disabled} value={tool.script} onChange={event => onChange({ ...value, tools: tools.map((item, i) => i === index ? { ...item, script: event.target.value } : item) })} /></label><label><span>Install timeout seconds {index + 1}</span><input required type="number" min={1} max={3600} disabled={disabled} value={tool.timeoutSeconds} onChange={event => onChange({ ...value, tools: tools.map((item, i) => i === index ? { ...item, timeoutSeconds: Number(event.target.value) } : item) })} /></label><button className="secondary-button" type="button" disabled={disabled} onClick={() => onChange({ ...value, tools: tools.filter((_, i) => i !== index) })}>Remove tool {index + 1}</button></fieldset>)}<button className="secondary-button" type="button" disabled={disabled} onClick={() => onChange({ ...value, tools: [...tools, { name: "", shell: "sh", script: "", timeoutSeconds: 300 }] })}>Add tool install</button></section>
    <section className="environment-extension" aria-label="MCP servers"><h3>MCP servers</h3><p className="muted">AI tasks use selected servers through their supported agent harness. Authentication refers to a step secret alias; enter no credentials here.</p>{servers.map((item, index) => <fieldset key={index}><legend>MCP server {index + 1}</legend><label><span>MCP name {index + 1}</span><input required disabled={disabled} value={item.name} onChange={event => server(index, { name: event.target.value })} /></label><label><span>MCP transport {index + 1}</span><select disabled={disabled} value={item.transport} onChange={event => server(index, { transport: event.target.value as "stdio" | "http", command: null, url: null, arguments: [], bearerTokenEnvironmentVariable: null, headerEnvironmentVariables: {}, environmentVariables: {} })}><option value="stdio">Standard input/output</option><option value="http">Streamable HTTP</option></select></label>{item.transport === "stdio" ? <><label><span>MCP command {index + 1}</span><input required disabled={disabled} value={item.command ?? ""} onChange={event => server(index, { command: event.target.value })} /></label><fieldset><legend>MCP arguments {index + 1}</legend>{(item.arguments ?? []).map((argument, argumentIndex) => <div key={argumentIndex}><label><span>MCP {index + 1} argument {argumentIndex + 1}</span><input disabled={disabled} value={argument} onChange={event => server(index, { arguments: (item.arguments ?? []).map((value, i) => i === argumentIndex ? event.target.value : value) })} /></label><button className="secondary-button" type="button" disabled={disabled} onClick={() => server(index, { arguments: (item.arguments ?? []).filter((_, i) => i !== argumentIndex) })}>Remove MCP {index + 1} argument {argumentIndex + 1}</button></div>)}<button className="secondary-button" type="button" disabled={disabled} onClick={() => server(index, { arguments: [...(item.arguments ?? []), ""] })}>Add MCP {index + 1} argument</button></fieldset></> : <><label><span>MCP URL {index + 1}</span><input required type="url" disabled={disabled} value={item.url ?? ""} onChange={event => server(index, { url: event.target.value })} /></label><label><span>MCP bearer token secret alias {index + 1}</span><input disabled={disabled} value={item.bearerTokenEnvironmentVariable ?? ""} onChange={event => server(index, { bearerTokenEnvironmentVariable: event.target.value || null })} /></label><Pairs label={`MCP ${index + 1} header secret aliases`} value={item.headerEnvironmentVariables ?? {}} disabled={disabled} onChange={headerEnvironmentVariables => server(index, { headerEnvironmentVariables })} /></>}
      {item.transport === "stdio" && <Pairs label={`MCP ${index + 1} environment secret aliases`} value={item.environmentVariables ?? {}} disabled={disabled} onChange={environmentVariables => server(index, { environmentVariables })} />}<button className="secondary-button" type="button" disabled={disabled} onClick={() => onChange({ ...value, mcpServers: servers.filter((_, i) => i !== index) })}>Remove MCP server {index + 1}</button></fieldset>)}<button className="secondary-button" type="button" disabled={disabled} onClick={() => onChange({ ...value, mcpServers: [...servers, { name: "", transport: "stdio", command: "", arguments: [], environmentVariables: {}, headerEnvironmentVariables: {} }] })}>Add MCP server</button></section>
  </>;
}
