import { useEffect, useRef, useState } from "react";
import { useBeforeUnload, useBlocker } from "react-router-dom";
import { ApiError, archiveImage, cancelImageBuild, createImage, imageConfiguration, listImageBuilds, listImages, queueImageBuild, updateImage, type ImageBuild, type ImageConfiguration, type ManagedImage, type ManagedImageInput } from "./api";

const empty = (base: string): ManagedImageInput => ({ name: "", description: "", source: { dockerfile: `FROM ${base || "docker.io/limeray/hhnl-formicae-worker:0.22.0"}\n\n# Install task tools here. Keep the Formicae worker runtime.\n`, ref: "main", dockerfilePath: "Dockerfile", contextPath: ".", platform: "linux/amd64" } });
const formFor = (image: ManagedImage): ManagedImageInput => ({ name: image.name, description: image.description, source: image.source });
const terminal = (build: ImageBuild) => ["Ready", "Failed", "Cancelled", "TimedOut"].includes(build.state);
export default function ImagesPage({ canAdminister }: { canAdminister: boolean }) {
  const [images, setImages] = useState<ManagedImage[]>([]), [selected, setSelected] = useState<ManagedImage>();
  const [configuration, setConfiguration] = useState<ImageConfiguration>(), [builds, setBuilds] = useState<ImageBuild[]>([]);
  const [form, setForm] = useState<ManagedImageInput>(empty("")), [baseline, setBaseline] = useState<ManagedImageInput>(empty(""));
  const [query, setQuery] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [conflict, setConflict] = useState(false), [confirmArchive, setConfirmArchive] = useState(false), [pending, setPending] = useState<(() => void)>();
  const dialog = useRef<HTMLDialogElement>(null);
  const dirty = JSON.stringify(form) !== JSON.stringify(baseline), blocker = useBlocker(dirty && canAdminister);
  const editable = canAdminister && !busy;
  useBeforeUnload(event => { if (dirty && canAdminister) { event.preventDefault(); event.returnValue = ""; } });
  const choose = (image?: ManagedImage, base = configuration?.workerBaseImage ?? "") => { const next = image ? formFor(image) : empty(base); setSelected(image); setForm(next); setBaseline(next); setError(""); setNotice(""); setConflict(false); setBuilds([]); };
  const guard = (action: () => void) => { if (dirty) setPending(() => action); else action(); };
  useEffect(() => { let active = true; Promise.all([listImages(), imageConfiguration()]).then(([items, config]) => { if (active) { setImages(items); setConfiguration(config); choose(items[0], config.workerBaseImage); } }).catch(e => { if (active) setError(String(e)); }); return () => { active = false; }; }, []);
  useEffect(() => { if (!selected) return; let active = true; const refresh = () => listImageBuilds(selected.id).then(items => { if (active) setBuilds(items); }).catch(e => { if (active) setError(String(e)); }); void refresh(); const interval = window.setInterval(refresh, 2000); return () => { active = false; clearInterval(interval); }; }, [selected?.id]);
  const showDialog = confirmArchive || !!pending || blocker.state === "blocked";
  useEffect(() => { if (showDialog) dialog.current?.showModal(); }, [showDialog]);
  const cancel = () => { setConfirmArchive(false); setPending(undefined); if (blocker.state === "blocked") blocker.reset(); };
  async function act(action: () => Promise<void>) { setBusy(true); setError(""); setNotice(""); try { await action(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); setConflict(e instanceof ApiError && e.status === 409); } finally { setBusy(false); } }
  async function save(event: React.FormEvent) { event.preventDefault(); if (!editable || conflict) return; await act(async () => { const saved = selected ? await updateImage(selected.id, form, selected.revision) : await createImage(form); choose(saved); setImages(await listImages()); setNotice("Image source saved. Build it to prepare a selectable image."); }); }
  const source = (patch: Partial<ManagedImageInput["source"]>) => setForm({ ...form, source: { ...form.source, ...patch } });
  const ready = builds.find(item => item.state === "Ready");
  return <section className="personas-page images-page"><div className="panel-heading"><h2>Images</h2><button type="button" className="secondary-button" disabled={!editable} onClick={() => guard(() => choose())}>New image</button></div>
    <p className="muted">Build worker-compatible images here, then select a prepared build in an agent task or environment.</p>
    {configuration?.developmentAdapter && <p role="status">Development adapter: builds are simulated. Production uses Kubernetes and your configured registry.</p>}
    {configuration && !configuration.enabled && <p role="status">Image builds are disabled. An operator must configure the registry and build namespace.</p>}
    {error && <p role="alert" className="error-text">{error}</p>}{notice && <p role="status" className="success-text">{notice}</p>}
    <div className="personas-layout"><aside className="panel"><label><span>Search images</span><input value={query} onChange={e => setQuery(e.target.value)} /></label>{images.filter(image => `${image.name} ${image.description}`.toLowerCase().includes(query.toLowerCase())).map(image => <button type="button" className={`ai-profile-button${selected?.id === image.id ? " active" : ""}`} key={image.id} onClick={() => guard(() => choose(image))}><strong>{image.name}</strong><span>Source revision {image.revision}</span></button>)}{images.length === 0 && <p>No images prepared yet.</p>}</aside>
      <section className="panel"><form onSubmit={save}><h3>{selected ? selected.name : "New image"}</h3><label><span>Image name</span><input required maxLength={120} disabled={!editable} value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label><span>Description</span><textarea maxLength={2000} disabled={!editable} value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label>
        <label><span>Build source</span><select disabled={!editable} value={form.source.repositoryUrl == null ? "inline" : "repository"} onChange={e => source(e.target.value === "inline" ? { repositoryUrl: null, dockerfile: empty(configuration?.workerBaseImage ?? "").source.dockerfile } : { repositoryUrl: "", dockerfile: "" })}><option value="inline">Inline Dockerfile</option><option value="repository">Connected repository</option></select></label>
        {form.source.repositoryUrl == null ? <><label><span>Dockerfile</span><textarea aria-label="Dockerfile" className="image-dockerfile" required rows={12} disabled={!editable} value={form.source.dockerfile} onChange={e => source({ dockerfile: e.target.value })} /></label><label><span>Load Dockerfile</span><input type="file" disabled={!editable} onChange={async e => { const file = e.target.files?.[0]; if (!file) return; if (file.size > 65536) { setError("Dockerfile must be at most 65536 bytes."); return; } source({ dockerfile: await file.text() }); }} /></label><p className="muted">Inline builds have an empty context. Use a connected repository when COPY needs project files. Build arguments must contain no credentials.</p></> : <><label><span>Connected repository URL</span><input type="url" required disabled={!editable} value={form.source.repositoryUrl} onChange={e => source({ repositoryUrl: e.target.value })} /></label><label><span>Repository branch</span><input required disabled={!editable} value={form.source.ref} onChange={e => source({ ref: e.target.value })} /></label><label><span>Dockerfile path</span><input required disabled={!editable} value={form.source.dockerfilePath} onChange={e => source({ dockerfilePath: e.target.value })} /></label><label><span>Context path</span><input required disabled={!editable} value={form.source.contextPath} onChange={e => source({ contextPath: e.target.value })} /></label><p className="muted">Each build pins the repository commit and respects .dockerignore. Paths must remain inside the repository.</p></>}
        <label><span>Target stage (optional)</span><input disabled={!editable} value={form.source.target ?? ""} onChange={e => source({ target: e.target.value || null })} /></label>
        <div className="button-row"><button type="submit" className="primary-button" disabled={!editable || conflict || !dirty}>{busy ? "Saving" : "Save image"}</button>{selected && <><button type="button" className="secondary-button" disabled={!editable || dirty || !configuration?.enabled || conflict} onClick={() => void act(async () => { await queueImageBuild(selected.id, selected.revision); setBuilds(await listImageBuilds(selected.id)); setNotice("Image build queued. Task selections stay unchanged."); })}>Build image</button><button type="button" className="secondary-button danger-button" disabled={!editable} onClick={() => setConfirmArchive(true)}>Archive image</button></>}</div>
        {conflict && selected && <button type="button" onClick={() => void act(async () => { const items = await listImages(); setImages(items); choose(items.find(x => x.id === selected.id)); })}>Reload current image</button>}
      </form>
      <section aria-label="Image build history"><h3>Build history</h3>{ready && <p>Prepared build: source revision {ready.sourceRevision}. Rebuilding does not change saved task selections.</p>}{builds.map(build => <article className="image-build" key={build.id}><h4>Revision {build.sourceRevision} · {build.state}</h4><p className="muted">Build {build.id} · {new Date(build.createdAt).toLocaleString()}</p>{build.commitSha && <p>Commit: <code>{build.commitSha}</code></p>}{build.reference && <p className="image-reference"><code>{build.reference}</code></p>}{build.failure && <p role="alert" className="error-text">{build.failure}</p>}{!terminal(build) && <button type="button" disabled={!editable} onClick={() => void act(async () => { await cancelImageBuild(selected!.id, build.id); setBuilds(await listImageBuilds(selected!.id)); })}>Cancel build {build.id.slice(0, 8)}</button>}<details><summary>Build logs {build.id.slice(0, 8)}</summary><pre className="image-build-logs">{build.logs || "Waiting for build logs."}</pre></details></article>)}{builds.length === 0 && <p>No builds yet.</p>}</section></section></div>
    {showDialog && <dialog ref={dialog} className="editor-confirm-dialog" onCancel={e => { e.preventDefault(); cancel(); }}><h3>{confirmArchive ? "Archive image?" : "Discard image changes?"}</h3><p>{confirmArchive ? "Future selection will be disabled. Saved workflows retain their pinned images." : "Unsaved source changes will be lost."}</p><div className="button-row"><button autoFocus type="button" onClick={cancel}>Cancel</button><button type="button" onClick={() => { if (confirmArchive) { setConfirmArchive(false); void act(async () => { await archiveImage(selected!.id, selected!.revision); choose(); setImages(await listImages()); setNotice("Image archived. Pinned artifacts are retained."); }); } else if (pending) { const action = pending; setPending(undefined); action(); } else if (blocker.state === "blocked") blocker.proceed(); }}>{confirmArchive ? "Archive" : "Discard"}</button></div></dialog>}
  </section>;
}
